import React,{useEffect,useMemo,useState} from 'react';
import {Alert,FlatList,Image,Linking,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import * as Notifications from 'expo-notifications';
import {StatusBar} from 'expo-status-bar';
import {createClient} from '@supabase/supabase-js';
const URL=process.env.EXPO_PUBLIC_SUPABASE_URL||'',KEY=process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY||''; const sb=createClient(URL,KEY);
const empty={title:'',type:'Plot',location:'',area:'',price:'Price on enquiry',description:'',status:'Available',latitude:'',longitude:'',map_url:'',featured:false,published:true,seo_title:'',seo_description:'',meta_keywords:''};
const settingKeys=['site_name','domain','whatsapp','phone','email','address','hero_title','hero_text','seo_title','seo_description','seo_keywords','google_business_url','facebook_url','instagram_url'];
export default function App(){
 const [session,setSession]=useState(null),[tab,setTab]=useState('dashboard'),[p,setP]=useState([]),[e,setE]=useState([]),[settings,setSettings]=useState({}),[search,setSearch]=useState(''),[form,setForm]=useState(empty),[photos,setPhotos]=useState([]),[editing,setEditing]=useState(null),[loading,setLoading]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 useEffect(()=>{sb.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=sb.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]); useEffect(()=>{if(session){refresh();registerPush()}},[session]);
 async function refresh(){setLoading(true);const [a,b,c]=await Promise.all([sb.from('properties').select('*,property_photos(*)').order('created_at',{ascending:false}),sb.from('enquiries').select('*,properties(title)').order('created_at',{ascending:false}),sb.from('site_settings').select('*')]);setLoading(false);const er=a.error||b.error||c.error;if(er)return Alert.alert('Error',er.message);setP(a.data||[]);setE(b.data||[]);const o={};(c.data||[]).forEach(x=>o[x.key]=x.value);setSettings(o)}
 async function login(){setLoading(true);const {error}=await sb.auth.signInWithPassword({email,password});setLoading(false);if(error)Alert.alert('Login failed',error.message)}
 async function registerPush(){try{const perm=await Notifications.requestPermissionsAsync();if(!perm.granted)return;const token=(await Notifications.getExpoPushTokenAsync()).data;await sb.from('admin_devices').upsert({user_id:session.user.id,expo_push_token:token,device_name:'SP Properties Android',active:true},{onConflict:'user_id,expo_push_token'})}catch{} }
 async function pick(){const perm=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!perm.granted)return Alert.alert('Permission needed','Allow photo access.');const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,quality:.82});if(!r.canceled)setPhotos([...photos,...r.assets])}
 async function uploadPhotos(id){if(!photos.length)return;const rows=[];for(let i=0;i<photos.length;i++){const a=photos[i];if(a.public_url){rows.push({property_id:id,storage_path:a.storage_path,public_url:a.public_url,sort_order:i});continue}const ext=(a.fileName?.split('.').pop()||'jpg').toLowerCase(),path=`${id}/${Date.now()}-${i}.${ext}`,blob=await (await fetch(a.uri)).blob();const {error}=await sb.storage.from('property-photos').upload(path,blob,{contentType:a.mimeType||'image/jpeg',upsert:true});if(error)throw error;const {data}=sb.storage.from('property-photos').getPublicUrl(path);rows.push({property_id:id,storage_path:path,public_url:data.publicUrl,sort_order:i})}await sb.from('property_photos').delete().eq('property_id',id);if(rows.length)await sb.from('property_photos').insert(rows)}
 async function save(){if(!form.title||!form.location||!form.area)return Alert.alert('Required','Title, location and area are required.');setLoading(true);try{const payload={...form,latitude:form.latitude?Number(form.latitude):null,longitude:form.longitude?Number(form.longitude):null};let id=editing;if(id){const {error}=await sb.from('properties').update(payload).eq('id',id);if(error)throw error}else{const {data,error}=await sb.from('properties').insert(payload).select().single();if(error)throw error;id=data.id}await uploadPhotos(id);await sb.from('audit_log').insert({user_id:session.user.id,action:id?'update_property':'create_property',entity:'properties',entity_id:id,details:{title:form.title}});reset();await refresh();setTab('properties')}catch(x){Alert.alert('Save failed',x.message)}finally{setLoading(false)}}
 function reset(){setForm(empty);setPhotos([]);setEditing(null)} function edit(x){setEditing(x.id);setForm({...empty,...x,latitude:x.latitude?.toString()||'',longitude:x.longitude?.toString()||''});setPhotos(x.property_photos||[]);setTab('form')}
 function remove(x){Alert.alert('Delete listing?',x.title,[{text:'Cancel'},{text:'Delete',style:'destructive',onPress:async()=>{await sb.from('properties').delete().eq('id',x.id);refresh()}}])}
 async function setEnq(id,status){await sb.from('enquiries').update({status}).eq('id',id);refresh()}
 async function saveSetting(key,value){await sb.from('site_settings').upsert({key,value,updated_at:new Date().toISOString()});setSettings({...settings,[key]:value})}
 const visible=useMemo(()=>p.filter(x=>(x.title+' '+x.location+' '+x.area).toLowerCase().includes(search.toLowerCase())),[p,search]);
 if(!URL||!KEY)return <Center><Text style={st.logo}>SP</Text><Text style={st.h1}>SP Properties Master V3</Text><Text style={st.muted}>Configure Supabase in mobile/.env.</Text></Center>;
 if(!session)return <Center><Text style={st.logo}>SP</Text><Text style={st.h1}>Master Control Center</Text><Text style={st.muted}>Manage www.sp-properties.com</Text><Input value={email} set={setEmail} ph="Admin email"/><Input value={password} set={setPassword} ph="Password" secure/><Btn t={loading?'Signing in…':'Sign in'} on={login}/></Center>;
 return <SafeAreaView style={st.root}><StatusBar style="dark"/><View style={st.header}><View><Text style={st.brand}>SP PROPERTIES</Text><Text style={st.sub}>MASTER CONTROL V3</Text></View><Pressable onPress={()=>sb.auth.signOut()}><Text style={st.link}>Logout</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={st.nav}>{[['dashboard','Dashboard'],['properties','Properties'],['enquiries','Enquiries'],['form','+ Add'],['settings','Website']].map(([k,t])=><Pressable key={k} onPress={()=>{if(k==='form')reset();setTab(k)}} style={[st.navItem,tab===k&&st.navOn]}><Text style={tab===k?st.navTextOn:st.navText}>{t}</Text></Pressable>)}</ScrollView>{tab==='dashboard'&&<Dashboard p={p} e={e} s={settings} go={setTab}/>} {tab==='properties'&&<View style={{flex:1}}><Input value={search} set={setSearch} ph="Search listings…"/><FlatList data={visible} keyExtractor={x=>x.id} refreshing={loading} onRefresh={refresh} contentContainerStyle={st.list} renderItem={({item})=><Property x={item} edit={()=>edit(item)} del={()=>remove(item)}/>} /></View>} {tab==='enquiries'&&<FlatList data={e} keyExtractor={x=>x.id} refreshing={loading} onRefresh={refresh} contentContainerStyle={st.list} renderItem={({item})=><Enquiry x={item} set={setEnq}/>} />} {tab==='form'&&<Editor f={form} set={setForm} photos={photos} pick={pick} save={save} loading={loading} editing={editing}/>} {tab==='settings'&&<Settings data={settings} save={saveSetting}/>}</SafeAreaView>}
function Center({children}){return <SafeAreaView style={st.center}>{children}</SafeAreaView>} function Input({value,set,ph,secure}){return <TextInput style={st.input} value={value} onChangeText={set} placeholder={ph} secureTextEntry={secure}/>} function Btn({t,on,dark}){return <Pressable style={[st.btn,dark&&st.dark]} onPress={on}><Text style={st.btnText}>{t}</Text></Pressable>}
function Dashboard({p,e,s,go}){return <ScrollView contentContainerStyle={st.pad}><Text style={st.h1}>Website Control</Text><Text style={st.muted}>One app for listings, enquiries, SEO and website content.</Text><View style={st.stats}>{[['Listings',p.length],['Available',p.filter(x=>x.status==='Available').length],['Featured',p.filter(x=>x.featured).length],['New Enquiries',e.filter(x=>x.status==='New').length]].map(([a,b])=><View style={st.stat} key={a}><Text style={st.big}>{b}</Text><Text style={st.muted}>{a}</Text></View>)}</View><View style={st.panel}><Text style={st.card}>Homepage</Text><Text style={st.body}>{s.hero_title||'Plots & Agricultural Land in Kharkhoda'}</Text><Text style={st.muted}>{s.hero_text||''}</Text><Text style={st.muted}>SEO: {s.seo_title||'Not set'}</Text></View><Btn t="Manage Properties" on={()=>go('properties')}/><Btn t="Website & SEO" on={()=>go('settings')} dark/></ScrollView>}
function Property({x,edit,del}){return <View style={st.cardBox}>{x.property_photos?.[0]?.public_url&&<Image source={{uri:x.property_photos[0].public_url}} style={st.thumb}/>}<Text style={st.card}>{x.title}</Text><Text style={st.muted}>{x.type} • {x.status} • {x.area}</Text><Text style={st.body}>{x.location} • {x.price}</Text><Text style={st.muted}>{x.featured?'⭐ Featured • ':''}{x.published?'Published':'Hidden'}</Text><View style={st.row}><Btn t="Edit" on={edit}/><Btn t="Delete" on={del} dark/></View></View>}
function Enquiry({x,set}){return <View style={st.cardBox}><Text style={st.card}>{x.name} • {x.status}</Text><Text style={st.body}>{x.properties?.title||'General enquiry'}</Text><Text style={st.muted}>{x.phone}</Text><Text style={st.body}>{x.message}</Text><View style={st.row}><Btn t="Contacted" on={()=>set(x.id,'Contacted')}/><Btn t="Closed" on={()=>set(x.id,'Closed')} dark/><Btn t="WhatsApp" on={()=>Linking.openURL('https://wa.me/'+String(x.phone).replace(/\D/g,''))}/></View></View>}
const fields=[['title','Title'],['location','Location'],['area','Area'],['price','Price'],['description','Description'],['map_url','Google Maps URL'],['latitude','Latitude'],['longitude','Longitude'],['seo_title','SEO title'],['seo_description','SEO description'],['meta_keywords','SEO keywords']];
function Editor({f,set,photos,pick,save,loading,editing}){return <ScrollView contentContainerStyle={st.pad}>{<Text style={st.h1}>{editing?'Edit':'Add'} Property</Text>}{fields.map(([k,l])=><Input key={k} value={String(f[k]??'')} set={v=>set({...f,[k]:v})} ph={l}/>)}<Text style={st.muted}>Type</Text><View style={st.row}>{['Plot','Agricultural Land'].map(v=><Btn key={v} t={v} on={()=>set({...f,type:v})}/>)}</View><Text style={st.muted}>Status</Text><View style={st.row}>{['Available','Reserved','Sold'].map(v=><Btn key={v} t={v} on={()=>set({...f,status:v})}/>)}</View><View style={st.row}><Btn t={f.featured?'★ Featured':'☆ Feature'} on={()=>set({...f,featured:!f.featured})}/><Btn t={f.published?'Published':'Hidden'} on={()=>set({...f,published:!f.published})}/></View><Btn t="Choose property photos" on={pick}/><Text style={st.muted}>{photos.length} photo(s) selected</Text><Btn t={loading?'Saving…':'Save Property'} on={save} dark/></ScrollView>}
function Settings({data,save}){const [local,setLocal]=useState(data);useEffect(()=>setLocal(data),[data]);return <ScrollView contentContainerStyle={st.pad}><Text style={st.h1}>Website & SEO</Text><Text style={st.muted}>Changes here are used by the public website.</Text>{settingKeys.map(k=><View key={k}><Text style={st.muted}>{k}</Text><Input value={local[k]||''} set={v=>setLocal({...local,[k]:v})} ph={k}/><Btn t={'Save '+k} on={()=>save(k,local[k]||'')}/></View>)}</ScrollView>}
const st=StyleSheet.create({root:{flex:1,backgroundColor:'#f7f7f5'},center:{flex:1,justifyContent:'center',padding:24,backgroundColor:'#f7f7f5'},header:{padding:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:'#fff'},brand:{fontWeight:'900',fontSize:19,letterSpacing:1},sub:{fontSize:10,letterSpacing:2,color:'#777'},logo:{fontSize:48,fontWeight:'900'},h1:{fontSize:28,fontWeight:'900',marginBottom:8},muted:{color:'#6d6d6d',marginVertical:5},body:{fontSize:15,marginVertical:6},link:{fontWeight:'700'},nav:{padding:10,gap:8},navItem:{paddingVertical:10,paddingHorizontal:14,borderRadius:20,backgroundColor:'#fff'},navOn:{backgroundColor:'#111'},navText:{color:'#111'},navTextOn:{color:'#fff'},pad:{padding:18,gap:10},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#ddd',borderRadius:12,padding:13,marginVertical:6},btn:{backgroundColor:'#caa76a',padding:12,borderRadius:10,marginVertical:5,alignItems:'center',flex:1},dark:{backgroundColor:'#111'},btnText:{color:'#fff',fontWeight:'800'},stats:{flexDirection:'row',flexWrap:'wrap',gap:10,marginVertical:15},stat:{backgroundColor:'#fff',padding:18,borderRadius:16,width:'47%'},big:{fontSize:28,fontWeight:'900'},panel:{backgroundColor:'#fff',padding:18,borderRadius:16,marginVertical:10},cardBox:{backgroundColor:'#fff',padding:14,borderRadius:16,marginBottom:10},card:{fontSize:17,fontWeight:'800'},thumb:{height:150,borderRadius:12,marginBottom:10},row:{flexDirection:'row',gap:7},list:{padding:14,paddingBottom:40}});
